services:
    nginx:
        image: nginx:alpine
        container_name: restaurant-nginx
        ports:
            - 8000:80
            - 443:443
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        depends_on:
            - app
        networks:
            - restaurant

    app:
        container_name: restaurant-app
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www
        depends_on:
            - db
        networks:
            - restaurant

    db:
        image: mysql:8.0
        container_name: restaurant-db
        volumes:
            - ./.docker/storage/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-root}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE:-laravel}'
            MYSQL_USER: '${DB_USERNAME:-username}'
            MYSQL_PASSWORD: '${DB_PASSWORD:-userpass}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        ports:
            - 8803:3306
        networks:
            - restaurant

    redis:
        image: redis:alpine
        container_name: restaurant-redis
        networks:
            - restaurant

    nodejs:
        build:
            context: ./docker/nodejs
            dockerfile: Dockerfile
        container_name: restaurant-nodejs
        volumes:
            - ./:/var/www
        tty: true
        ports:
            - 5173:5173
        networks:
            - restaurant

networks:
    restaurant:
        name: restaurant
        driver: bridge




